openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contancts app
tags:
  - name: Contacts
    description: API for managing contacts
  - name: Auth
    description: API for user authentication and authorization
servers:
  - url: http://localhost:3000
  - url: https://contacts-zu4u.onrender.com
paths:
  /contacts:
    get: 
      $ref: ../swagger/paths/contacts/get.yaml
    post: 
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete: 
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch: 
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
  /auth/register:
    post: 
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post: 
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post: 
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
